name: Plugin Asset/Readme Update
on:
  push:
    branches:
      - master

jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org Plugin Asset/Readme Update
        if: contains( steps.svn_access.outputs.has_access, 'yes')
        uses: 10up/action-wordpress-plugin-asset-update@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          ASSETS_DIR: .github/wordpress-org-assets
